from math import*
print("Введите x:  ")
x = float(input())
print("Введите а:  ")
a = float(input())
G = -((7) * (20 *(a**2) + 11 * a * x - ( 45 * (x**2)))) / (3 *(a**2) - 7 * a * x + 4 *(x**2))
print(G)
print("Введите x:  ")
x = float(input())
print("Введите а:  ")
a = float(input())
F = (tan(60 * (a **2) + 88 * (a * x) + 21 * (x**2)))
print(F)
print("Введите x:  ")
x = float(input())
print("Введите а:  ")
a = float(input())
Y = log((-40) * (a ** 2) + 3 * (a * x) + (x ** 2) + 1)/log(2)
print(Y)
